# Generated by Django 5.0.7 on 2025-04-11 15:08

import django.core.validators
import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="TaskSchedule",
            fields=[
                (
                    "task_schedule_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "operation",
                    models.TextField(
                        validators=[tasks.models.validate_addition_operation]
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
                (
                    "every_x_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "every_x_hours",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "schedule_x_times",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "checked_scheduling_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "operation",
                    models.TextField(
                        validators=[tasks.models.validate_addition_operation]
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                            ("ERROR", "ERROR"),
                        ],
                        default=tasks.models.TaskStatus["PENDING"],
                        max_length=10,
                    ),
                ),
                ("result", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="tasks.taskschedule",
                    ),
                ),
            ],
        ),
    ]
