# Generated by Django 5.0.7 on 2025-04-12 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskschedule",
            name="schedule_x_times",
            field=models.PositiveIntegerField(
                db_index=True,
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
