name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and start Docker containers
        run: docker compose up -d --build

      - name: Run pre-commit script
        run: ./misc/pre-commit.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and start Docker containers
        run: docker compose up -d --build

      - name: Run pre-push script
        run: ./misc/pre-push.sh
